// EarnMart Deterministic Seed Data
// Spec Reference: Section 8 & Section 4

import { Category, Product, LearningQuestion, WordPair, DailyMission } from '../types';

export const SEED_CATEGORIES: Category[] = [
  { id: 'cat-all', name: 'Tất cả', slug: 'all', iconName: 'Sparkles', sortOrder: 1 },
  { id: 'cat-avatar', name: 'Phụ kiện avatar', slug: 'avatar-accessory', iconName: 'Smile', sortOrder: 2 },
  { id: 'cat-outfit', name: 'Trang phục', slug: 'outfit', iconName: 'Shirt', sortOrder: 3 },
  { id: 'cat-pet', name: 'Pet ảo', slug: 'virtual-pet', iconName: 'Dog', sortOrder: 4 },
  { id: 'cat-decor', name: 'Đồ trang trí', slug: 'decoration', iconName: 'Palette', sortOrder: 5 },
  { id: 'cat-box', name: 'Mystery Box', slug: 'mystery-box', iconName: 'Package', sortOrder: 6 },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod-01',
    categoryId: 'cat-pet',
    name: 'Cáo Tuyết Rừng Sâu (Forest Fox)',
    description: 'Một chú cáo lông trắng bồng bềnh luôn đi bên cạnh avatar của bạn, mang lại năng lượng tích cực.',
    usageDescription: 'Vật phẩm trang trí avatar và hiện diện trên trang cá nhân.',
    priceCoins: 120,
    stock: 50,
    imageUrl: 'https://images.unsplash.com/photo-1516934024742-b461fba47600?w=600&auto=format&fit=crop&q=80',
    badge: 'HOT',
    isActive: true,
    virtualType: 'PET',
    isPopular: true,
  },
  {
    id: 'prod-02',
    categoryId: 'cat-avatar',
    name: 'Mũ Len Xanh Biển (Cozy Blue Hat)',
    description: 'Mũ len ấm áp phối sắc xanh dương pastel vintage, phù hợp mọi phong cách mùa đông.',
    usageDescription: 'Trang bị trên đầu cho avatar hồ sơ.',
    priceCoins: 80,
    stock: null,
    imageUrl: 'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?w=600&auto=format&fit=crop&q=80',
    badge: 'BÁN CHẠY',
    isActive: true,
    virtualType: 'AVATAR_ACCESSORY',
    isPopular: true,
  },
  {
    id: 'prod-03',
    categoryId: 'cat-avatar',
    name: 'Balo Pixel Retro (Pixel Backpack)',
    description: 'Balo thiết kế đồ họa pixel 8-bit hoài niệm của thập niên 90.',
    usageDescription: 'Đeo sau lưng nhân vật ảo.',
    priceCoins: 100,
    stock: null,
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    virtualType: 'AVATAR_ACCESSORY',
  },
  {
    id: 'prod-04',
    categoryId: 'cat-decor',
    name: 'Khung Tên Hoàng Kim (Golden Nameplate)',
    description: 'Khung tên viền vàng lấp lánh khẳng định đẳng cấp chăm chỉ học tập.',
    usageDescription: 'Hiển thị viền vàng quanh tên của bạn trong bảng xếp hạng và hồ sơ.',
    priceCoins: 250,
    stock: 20,
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    badge: 'HIẾM',
    isActive: true,
    virtualType: 'DECORATION',
    isPopular: true,
  },
  {
    id: 'prod-05',
    categoryId: 'cat-decor',
    name: 'Chậu Sen Đá Mini (Mini Room Plant)',
    description: 'Chậu sen đá để bàn xanh tươi tượng trưng cho sự kiên trì bền bỉ mỗi ngày.',
    usageDescription: 'Trang trí góc phòng ảo của hồ sơ cá nhân.',
    priceCoins: 65,
    stock: null,
    imageUrl: 'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    virtualType: 'DECORATION',
  },
  {
    id: 'prod-06',
    categoryId: 'cat-outfit',
    name: 'Áo Khoác Ngân Hà (Starry Jacket)',
    description: 'Áo khoác bomber lấp lánh ánh sao vũ trụ rực rỡ.',
    usageDescription: 'Thay đổi diện mạo trang phục avatar.',
    priceCoins: 180,
    stock: null,
    imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop&q=80',
    badge: 'MỚI',
    isActive: true,
    virtualType: 'OUTFIT',
    isNew: true,
  },
  {
    id: 'prod-07',
    categoryId: 'cat-avatar',
    name: 'Kính Cyberpunk Neon',
    description: 'Kính râm tương lai với vệt sáng đa sắc rực rỡ.',
    usageDescription: 'Đeo trên khuôn mặt avatar ảo.',
    priceCoins: 95,
    stock: null,
    imageUrl: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    virtualType: 'AVATAR_ACCESSORY',
  },
  {
    id: 'prod-08',
    categoryId: 'cat-decor',
    name: 'Hào Quang Đôi Cánh (Angel Wings Aura)',
    description: 'Hiệu ứng ánh sáng cánh thiên thần tỏa hào quang dịu nhẹ.',
    usageDescription: 'Hiệu ứng hào quang bao quanh avatar.',
    priceCoins: 320,
    stock: 15,
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    badge: 'HÀNG HIẾM',
    isActive: true,
    virtualType: 'DECORATION',
  },
  {
    id: 'prod-09',
    categoryId: 'cat-pet',
    name: 'Mèo Thần Tài (Lucky Cat Statue)',
    description: 'Chú mèo vẫy tay may mắn mang lại hứng khởi cho các buổi làm bài quiz.',
    usageDescription: 'Đặt làm linh vật góc học tập.',
    priceCoins: 110,
    stock: null,
    imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    virtualType: 'PET',
  },
  {
    id: 'prod-10',
    categoryId: 'cat-outfit',
    name: 'Giày Sneaker Tia Chớp (Neon Sneakers)',
    description: 'Đôi giày thể thao phát sáng theo từng bước đi ảo của bạn.',
    usageDescription: 'Trang phục đôi chân avatar.',
    priceCoins: 140,
    stock: null,
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    virtualType: 'OUTFIT',
  },
  {
    id: 'prod-11',
    categoryId: 'cat-avatar',
    name: 'Mũ Thám Tử Cổ Điển (Detective Cap)',
    description: 'Phong cách Sherlock Holmes cho những bạn thích giải đố từ vựng.',
    usageDescription: 'Mũ đội cho nhân vật ảo.',
    priceCoins: 75,
    stock: null,
    imageUrl: 'https://images.unsplash.com/photo-1521369909029-2afed882baee?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    virtualType: 'AVATAR_ACCESSORY',
  },
  {
    id: 'prod-12',
    categoryId: 'cat-decor',
    name: 'Sách Ma Pháp Cổ (Magic Spellbook)',
    description: 'Quyển sách cổ bìa da phát sáng với những kiến thức tiếng Anh vô tận.',
    usageDescription: 'Trưng bày trong kho đồ sưu tầm ảo.',
    priceCoins: 160,
    stock: null,
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    virtualType: 'DECORATION',
  },
  {
    id: 'prod-13',
    categoryId: 'cat-outfit',
    name: 'Ván Trượt Tương Lai (Cyber Hoverboard)',
    description: 'Phương tiện lướt trên không gian mạng của thế hệ mới.',
    usageDescription: 'Tư thế đứng nổi bật của avatar.',
    priceCoins: 290,
    stock: 10,
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80',
    badge: 'GIỚI HẠN',
    isActive: true,
    virtualType: 'OUTFIT',
  },
  {
    id: 'prod-14',
    categoryId: 'cat-avatar',
    name: 'Trâm Cài Hoa Anh Đào (Sakura Hairpin)',
    description: 'Cành hoa anh đào nhỏ nhắn xinh xắn dành cho những ngày mùa xuân.',
    usageDescription: 'Cài lên mái tóc avatar.',
    priceCoins: 50,
    stock: null,
    imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    virtualType: 'AVATAR_ACCESSORY',
  },
  {
    id: 'prod-15',
    categoryId: 'cat-avatar',
    name: 'Vương Miện Hoàng Gia (Royal Crown)',
    description: 'Vương miện đính ngọc dành riêng cho những bạn kiên trì đạt streak cao nhất.',
    usageDescription: 'Đội trên đầu đại diện vị trí dẫn đầu.',
    priceCoins: 500,
    stock: 5,
    imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80',
    badge: 'HUYỀN THOẠI',
    isActive: true,
    virtualType: 'AVATAR_ACCESSORY',
  },
  {
    id: 'prod-16',
    categoryId: 'cat-avatar',
    name: 'Ly Cà Phê Năng Lượng (Coffee Cup)',
    description: 'Ly latte nóng hổi tiếp thêm động lực học 5 phút mỗi sáng.',
    usageDescription: 'Cầm trên tay nhân vật ảo.',
    priceCoins: 40,
    stock: null,
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    virtualType: 'AVATAR_ACCESSORY',
  },
  {
    id: 'prod-17',
    categoryId: 'cat-avatar',
    name: 'Đồng Hồ Hologram Thông Minh',
    description: 'Đồng hồ đếm bước chân và hiển thị số xu ảo với giao diện 3D.',
    usageDescription: 'Đeo ở cổ tay avatar.',
    priceCoins: 130,
    stock: null,
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    virtualType: 'AVATAR_ACCESSORY',
  },
  {
    id: 'prod-18',
    categoryId: 'cat-decor',
    name: 'Lều Cắm Trại Dã Ngoại (Camping Tent)',
    description: 'Chiếc lều cắm trại ấm cúng dưới bầu trời đêm ngàn sao.',
    usageDescription: 'Nền phong cảnh đại diện trang cá nhân.',
    priceCoins: 175,
    stock: null,
    imageUrl: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    virtualType: 'DECORATION',
  },
  {
    id: 'prod-19',
    categoryId: 'cat-avatar',
    name: 'Máy Ảnh Film Cổ Điển (Vintage Camera)',
    description: 'Chiếc máy ảnh film phong trần dành cho người đam mê xê dịch.',
    usageDescription: 'Phụ kiện đeo chéo người avatar.',
    priceCoins: 85,
    stock: null,
    imageUrl: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    virtualType: 'AVATAR_ACCESSORY',
  },
  {
    id: 'prod-20',
    categoryId: 'cat-pet',
    name: 'Bé Mây Lơ Lửng (Cloud Companion)',
    description: 'Đám mây đáng yêu luôn bay theo trên đầu che mát cho bạn khi chạy bộ.',
    usageDescription: 'Thú cưng bay lượn quanh avatar.',
    priceCoins: 210,
    stock: 30,
    imageUrl: 'https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=600&auto=format&fit=crop&q=80',
    badge: 'MỚI',
    isActive: true,
    virtualType: 'PET',
  },
  {
    id: 'prod-21',
    categoryId: 'cat-avatar',
    name: 'Mũ Phi Hành Gia (Astronaut Helmet)',
    description: 'Mũ thám hiểm vũ trụ với kính phản chiếu ánh sáng ngân hà.',
    usageDescription: 'Mũ bảo hộ toàn diện cho nhân vật ảo.',
    priceCoins: 240,
    stock: 25,
    imageUrl: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    virtualType: 'AVATAR_ACCESSORY',
  },
  {
    id: 'prod-22',
    categoryId: 'cat-decor',
    name: 'Đàn Guitar Pha Lê (Crystal Guitar)',
    description: 'Chiếc guitar trong suốt phát ra những giai điệu acoustic êm đềm.',
    usageDescription: 'Nhạc cụ trang trí phòng hồ sơ.',
    priceCoins: 350,
    stock: 12,
    imageUrl: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=600&auto=format&fit=crop&q=80',
    badge: 'HIẾM',
    isActive: true,
    virtualType: 'DECORATION',
  },
  {
    id: 'prod-23',
    categoryId: 'cat-box',
    name: 'Hộp Kỳ Bí EarnMart (Mystery Box I)',
    description: 'Hộp quà chứa ngẫu nhiên một vật phẩm trang trí giới hạn (Đã định sẵn trong bản MVP).',
    usageDescription: 'Mở khóa một vật phẩm sưu tầm ngẫu nhiên vào bộ sưu tập.',
    priceCoins: 150,
    stock: null,
    imageUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=80',
    badge: 'BẤT NGỜ',
    isActive: true,
    virtualType: 'MYSTERY_BOX',
  },
  {
    id: 'prod-24',
    categoryId: 'cat-outfit',
    name: 'Khăn Quàng Cầu Vồng (Rainbow Scarf)',
    description: 'Chiếc khăn quàng ấm áp với sắc màu tươi sáng tôn vinh sự đa dạng.',
    usageDescription: 'Phụ kiện giữ ấm cổ cho avatar.',
    priceCoins: 60,
    stock: null,
    imageUrl: 'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=600&auto=format&fit=crop&q=80',
    isActive: true,
    virtualType: 'OUTFIT',
  },
];

export const SEED_QUESTIONS: LearningQuestion[] = [
  // TOPIC 1: DAILY LIFE (10 questions)
  {
    id: 'q-dl-01',
    topic: 'DAILY_LIFE',
    topicLabel: 'Đời Sống Hằng Ngày',
    prompt: 'What time do you usually _____ up in the morning?',
    choices: ['wake', 'wakes', 'woke', 'waking'],
    correctAnswerIndex: 0,
    explanation: 'Với chủ ngữ "you" trong câu hỏi hiện tại đơn, ta dùng động từ nguyên thể "wake".',
  },
  {
    id: 'q-dl-02',
    topic: 'DAILY_LIFE',
    topicLabel: 'Đời Sống Hằng Ngày',
    prompt: 'Could you please _____ the salt across the table?',
    choices: ['pass', 'past', 'passed', 'passing'],
    correctAnswerIndex: 0,
    explanation: 'Sau trợ động từ "Could", động từ chính đi ở dạng nguyên thể không "to".',
  },
  {
    id: 'q-dl-03',
    topic: 'DAILY_LIFE',
    topicLabel: 'Đời Sống Hằng Ngày',
    prompt: 'I am looking forward to _____ from you soon.',
    choices: ['hear', 'hearing', 'heard', 'hears'],
    correctAnswerIndex: 1,
    explanation: 'Cụm từ "look forward to + V-ing" nghĩa là mong đợi điều gì.',
  },
  {
    id: 'q-dl-04',
    topic: 'DAILY_LIFE',
    topicLabel: 'Đời Sống Hằng Ngày',
    prompt: 'Don\'t forget to turn _____ the lights before leaving the room.',
    choices: ['in', 'off', 'up', 'over'],
    correctAnswerIndex: 1,
    explanation: '"Turn off" có nghĩa là tắt thiết bị điện.',
  },
  {
    id: 'q-dl-05',
    topic: 'DAILY_LIFE',
    topicLabel: 'Đời Sống Hằng Ngày',
    prompt: 'How much does this cup of coffee _____?',
    choices: ['cost', 'costs', 'costed', 'costing'],
    correctAnswerIndex: 0,
    explanation: 'Sau trợ động từ "does" trong câu hỏi, ta dùng động từ nguyên thể "cost".',
  },
  {
    id: 'q-dl-06',
    topic: 'DAILY_LIFE',
    topicLabel: 'Đời Sống Hằng Ngày',
    prompt: 'She enjoys _____ books in the cozy cafe on rainy days.',
    choices: ['read', 'to reading', 'reading', 'reads'],
    correctAnswerIndex: 2,
    explanation: 'Động từ "enjoy" luôn đi kèm với danh động từ V-ing.',
  },
  {
    id: 'q-dl-07',
    topic: 'DAILY_LIFE',
    topicLabel: 'Đời Sống Hằng Ngày',
    prompt: 'My brother is _____ than me at cooking.',
    choices: ['good', 'better', 'best', 'more good'],
    correctAnswerIndex: 1,
    explanation: 'So sánh hơn của "good" là "better".',
  },
  {
    id: 'q-dl-08',
    topic: 'DAILY_LIFE',
    topicLabel: 'Đời Sống Hằng Ngày',
    prompt: 'It\'s raining heavily, so we decided to stay _____ home.',
    choices: ['at', 'on', 'in', 'to'],
    correctAnswerIndex: 0,
    explanation: 'Cụm từ cố định chỉ ở nhà là "stay at home".',
  },
  {
    id: 'q-dl-09',
    topic: 'DAILY_LIFE',
    topicLabel: 'Đời Sống Hằng Ngày',
    prompt: 'There aren\'t _____ apples left in the basket.',
    choices: ['much', 'any', 'some', 'a'],
    correctAnswerIndex: 1,
    explanation: 'Trong câu phủ định với danh từ đếm được số nhiều, ta dùng "any".',
  },
  {
    id: 'q-dl-10',
    topic: 'DAILY_LIFE',
    topicLabel: 'Đời Sống Hằng Ngày',
    prompt: 'What are you planning to do _____ the weekend?',
    choices: ['on', 'at', 'with', 'for'],
    correctAnswerIndex: 0,
    explanation: '"On the weekend" (Mỹ) hoặc "at the weekend" (Anh) đều phổ biến, "on" là lựa chọn thông dụng.',
  },

  // TOPIC 2: OFFICE & WORK (10 questions)
  {
    id: 'q-of-01',
    topic: 'OFFICE',
    topicLabel: 'Công Sở & Công Việc',
    prompt: 'Let\'s schedule a meeting to _____ the quarterly progress.',
    choices: ['discuss', 'discuss about', 'discussion', 'discussing'],
    correctAnswerIndex: 0,
    explanation: '"Discuss" là ngoại động từ, theo sau trực tiếp là tân ngữ không cần giới từ "about".',
  },
  {
    id: 'q-of-02',
    topic: 'OFFICE',
    topicLabel: 'Công Sở & Công Việc',
    prompt: 'Please find the contract attached for your _____ .',
    choices: ['refer', 'review', 'revision', 'revised'],
    correctAnswerIndex: 1,
    explanation: '"For your review" là cụm từ văn phòng quen thuộc để người nhận kiểm tra/xem xét tài liệu.',
  },
  {
    id: 'q-of-03',
    topic: 'OFFICE',
    topicLabel: 'Công Sở & Công Việc',
    prompt: 'We need to submit the report _____ Friday at 5 PM.',
    choices: ['by', 'until', 'at', 'in'],
    correctAnswerIndex: 0,
    explanation: '"By" dùng để chỉ thời hạn cuối cùng (deadline) - trước hoặc đúng thời điểm đó.',
  },
  {
    id: 'q-of-04',
    topic: 'OFFICE',
    topicLabel: 'Công Sở & Công Việc',
    prompt: 'The manager asked everyone to be _____ time for the client presentation.',
    choices: ['in', 'on', 'at', 'with'],
    correctAnswerIndex: 1,
    explanation: '"On time" có nghĩa là đúng giờ (theo lịch hẹn chuẩn xác).',
  },
  {
    id: 'q-of-05',
    topic: 'OFFICE',
    topicLabel: 'Công Sở & Công Việc',
    prompt: 'Could you give me a _____ with printing these handouts?',
    choices: ['arm', 'hand', 'foot', 'finger'],
    correctAnswerIndex: 1,
    explanation: '"Give someone a hand" là thành ngữ có nghĩa là giúp đỡ ai đó.',
  },
  {
    id: 'q-of-06',
    topic: 'OFFICE',
    topicLabel: 'Công Sở & Công Việc',
    prompt: 'The new feature is currently _____ development and will launch next month.',
    choices: ['under', 'in', 'on', 'with'],
    correctAnswerIndex: 0,
    explanation: 'Cụm từ "under development" có nghĩa là đang trong quá trình phát triển.',
  },
  {
    id: 'q-of-07',
    topic: 'OFFICE',
    topicLabel: 'Công Sở & Công Việc',
    prompt: 'I apologize for the delayed reply; I was _____ of office yesterday.',
    choices: ['out', 'away', 'off', 'far'],
    correctAnswerIndex: 0,
    explanation: '"Out of office" (OOO) là cụm từ chuẩn chỉ trạng thái nghỉ làm/vắng mặt ở công ty.',
  },
  {
    id: 'q-of-08',
    topic: 'OFFICE',
    topicLabel: 'Công Sở & Công Việc',
    prompt: 'All employees are entitled _____ 14 days of annual paid leave.',
    choices: ['to', 'for', 'with', 'in'],
    correctAnswerIndex: 0,
    explanation: 'Cấu trúc "be entitled to something" mang nghĩa có quyền được hưởng điều gì.',
  },
  {
    id: 'q-of-09',
    topic: 'OFFICE',
    topicLabel: 'Công Sở & Công Việc',
    prompt: 'Let\'s wrap _____ this sprint retrospective and head to lunch.',
    choices: ['up', 'down', 'off', 'in'],
    correctAnswerIndex: 0,
    explanation: '"Wrap up" có nghĩa là tổng kết, kết thúc một cuộc họp hoặc sự kiện.',
  },
  {
    id: 'q-of-10',
    topic: 'OFFICE',
    topicLabel: 'Công Sở & Công Việc',
    prompt: 'Who is in _____ of the marketing campaign for the new product?',
    choices: ['charge', 'duty', 'control', 'lead'],
    correctAnswerIndex: 0,
    explanation: '"In charge of" có nghĩa là phụ trách, chịu trách nhiệm chính.',
  },

  // TOPIC 3: TRAVEL & LEISURE (10 questions)
  {
    id: 'q-tr-01',
    topic: 'TRAVEL',
    topicLabel: 'Du Lịch & Khám Phá',
    prompt: 'Excuse me, where can I _____ my boarding pass?',
    choices: ['collect', 'collected', 'collection', 'collecting'],
    correctAnswerIndex: 0,
    explanation: 'Sau động từ khuyết thiếu "can", động từ ở thể nguyên mẫu không "to".',
  },
  {
    id: 'q-tr-02',
    topic: 'TRAVEL',
    topicLabel: 'Du Lịch & Khám Phá',
    prompt: 'The flight from Tokyo to Paris has been _____ due to bad weather.',
    choices: ['delayed', 'delaying', 'delays', 'delay'],
    correctAnswerIndex: 0,
    explanation: 'Thể bị động thì hiện tại hoàn thành: "has been + V3/ed" (delayed).',
  },
  {
    id: 'q-tr-03',
    topic: 'TRAVEL',
    topicLabel: 'Du Lịch & Khám Phá',
    prompt: 'I\'d like to make a reservation _____ two nights, please.',
    choices: ['for', 'at', 'on', 'with'],
    correctAnswerIndex: 0,
    explanation: 'Đặt phòng cho một khoảng thời gian: "reservation for [duration]".',
  },
  {
    id: 'q-tr-04',
    topic: 'TRAVEL',
    topicLabel: 'Du Lịch & Khám Phá',
    prompt: 'Is breakfast _____ in the room rate?',
    choices: ['included', 'contained', 'consisted', 'composed'],
    correctAnswerIndex: 0,
    explanation: '"Included in" có nghĩa là đã bao gồm trong chi phí dịch vụ.',
  },
  {
    id: 'q-tr-05',
    topic: 'TRAVEL',
    topicLabel: 'Du Lịch & Khám Phá',
    prompt: 'Which platform does the express train to Kyoto depart _____?',
    choices: ['from', 'to', 'for', 'at'],
    correctAnswerIndex: 0,
    explanation: '"Depart from" mang nghĩa xuất phát, rời khỏi từ một địa điểm/sân ga.',
  },
  {
    id: 'q-tr-06',
    topic: 'TRAVEL',
    topicLabel: 'Du Lịch & Khám Phá',
    prompt: 'Make sure your passport is valid for at least six _____ before traveling abroad.',
    choices: ['months', 'days', 'weeks', 'hours'],
    correctAnswerIndex: 0,
    explanation: 'Quy định quốc tế thường yêu cầu hộ chiếu còn hạn ít nhất 6 tháng ("six months").',
  },
  {
    id: 'q-tr-07',
    topic: 'TRAVEL',
    topicLabel: 'Du Lịch & Khám Phá',
    prompt: 'Can you recommend a good local restaurant _____ authentic food?',
    choices: ['serving', 'serves', 'served', 'to serve'],
    correctAnswerIndex: 0,
    explanation: 'Mệnh đề quan hệ rút gọn dùng hiện tại phân từ V-ing (serving) mang nghĩa chủ động.',
  },
  {
    id: 'q-tr-08',
    topic: 'TRAVEL',
    topicLabel: 'Du Lịch & Khám Phá',
    prompt: 'We spent the afternoon _____ around the historic old town.',
    choices: ['wandering', 'wondering', 'wander', 'wandered'],
    correctAnswerIndex: 0,
    explanation: '"Spend time + V-ing": "wandering" mang nghĩa đi dạo thong thả ngắm cảnh.',
  },
  {
    id: 'q-tr-09',
    topic: 'TRAVEL',
    topicLabel: 'Du Lịch & Khám Phá',
    prompt: 'Do you have any items to _____ at customs?',
    choices: ['declare', 'announce', 'inform', 'notify'],
    correctAnswerIndex: 0,
    explanation: 'Tại hải quan sân bay, thủ tục khai báo hành lý được gọi là "declare".',
  },
  {
    id: 'q-tr-10',
    topic: 'TRAVEL',
    topicLabel: 'Du Lịch & Khám Phá',
    prompt: 'The view from the mountain top was absolutely _____ !',
    choices: ['breathtaking', 'breathed', 'breathless', 'breathe'],
    correctAnswerIndex: 0,
    explanation: '"Breathtaking" là tính từ chỉ phong cảnh đẹp ngoạn mục đến nghẹt thở.',
  },
];

export const SEED_WORD_PAIRS: WordPair[] = [
  { id: 'wp-01', english: 'Opportunity', vietnamese: 'Cơ hội', phonetic: '/ˌɒp.əˈtjuː.nə.ti/' },
  { id: 'wp-02', english: 'Perseverance', vietnamese: 'Sự kiên trì', phonetic: '/ˌpɜː.sɪˈvɪə.rəns/' },
  { id: 'wp-03', english: 'Achievement', vietnamese: 'Thành tựu', phonetic: '/əˈtʃiːv.mənt/' },
  { id: 'wp-04', english: 'Habit', vietnamese: 'Thói quen', phonetic: '/ˈhæb.ɪt/' },
  { id: 'wp-05', english: 'Discipline', vietnamese: 'Kỷ luật', phonetic: '/ˈdɪs.ə.plɪn/' },
  { id: 'wp-06', english: 'Knowledge', vietnamese: 'Kiến thức', phonetic: '/ˈnɒl.ɪdʒ/' },
  { id: 'wp-07', english: 'Motivation', vietnamese: 'Động lực', phonetic: '/ˌməʊ.tɪˈveɪ.ʃən/' },
  { id: 'wp-08', english: 'Progress', vietnamese: 'Tiến bộ', phonetic: '/ˈprəʊ.ɡres/' },
  { id: 'wp-09', english: 'Exploration', vietnamese: 'Sự khám phá', phonetic: '/ˌek.spləˈreɪ.ʃən/' },
  { id: 'wp-10', english: 'Reward', vietnamese: 'Phần thưởng', phonetic: '/rɪˈwɔːd/' },
  { id: 'wp-11', english: 'Endurance', vietnamese: 'Sức bền', phonetic: '/ɪnˈdʒʊə.rəns/' },
  { id: 'wp-12', english: 'Challenge', vietnamese: 'Thử thách', phonetic: '/ˈtʃæl.ɪndʒ/' },
];

export const SEED_MISSIONS: DailyMission[] = [
  {
    id: 'ms-01',
    key: 'DAILY_LOGIN',
    title: 'Điểm danh buổi sáng',
    description: 'Mở ứng dụng EarnMart và nhận quà chào ngày mới',
    target: 1,
    rewardCoins: 5,
    icon: 'CalendarCheck',
  },
  {
    id: 'ms-02',
    key: 'QUIZ_SESSION',
    title: 'Học tiếng Anh chăm chỉ',
    description: 'Hoàn thành 1 bài trắc nghiệm tiếng Anh 5 câu',
    target: 1,
    rewardCoins: 20,
    icon: 'BookOpen',
  },
  {
    id: 'ms-03',
    key: 'WORD_MATCH',
    title: 'Bậc thầy ghép từ',
    description: 'Chiến thắng 1 ván mini game Word Match',
    target: 1,
    rewardCoins: 10,
    icon: 'Zap',
  },
  {
    id: 'ms-04',
    key: 'WALK_CHALLENGE',
    title: 'Khởi động đôi chân',
    description: 'Thực hiện 1 phiên vận động đi bộ/chạy bộ mô phỏng',
    target: 1,
    rewardCoins: 15,
    icon: 'Footprints',
  },
  {
    id: 'ms-05',
    key: 'BROWSE_SHOP',
    title: 'Khám phá gian hàng ảo',
    description: 'Dạo xem các sản phẩm ảo độc đáo trong Shop',
    target: 3,
    rewardCoins: 5,
    icon: 'ShoppingBag',
  },
];

